language: node_js

node_js:
  - "12"

branches:
  only:
    - master
    - lab

cache: yarn

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
  - aws configure set aws_secret_access_key ${AWS_SECRET_KEY}
  - |
    if [ $TRAVIS_BRANCH == "lab" ]; then
       export BUILD_ENV=lab
    elif [ $TRAVIS_BRANCH == "staging" ]; then
       export BUILD_ENV=staging
    elif [ $TRAVIS_BRANCH == "master" ]; then
       export BUILD_ENV=master
    fi

install:
  - yarn

before_script:
  - yarn lint


jobs:
  deploy-common: &deploy-common
    provider: s3
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key: ${AWS_SECRET_KEY}
    bucket: ${AWS_S3_BUCKET}
    skip_cleanup: true
    on:
      branch:
        - master
        - lab
        - staging
  include:
    - stage: index
      script: 
        - yarn build-index:${BUILD_ENV}
      deploy:
      - <<: *deploy-common
        local_dir: "dist"
    - stage: landing
      script: 
        - yarn build-landing:${BUILD_ENV}
      deploy:
      - <<: *deploy-common
        local_dir: "dist"
