language: node_js

node_js:
  - "12"

branches:
  only:
    - master
    - lab

cache: yarn

install:
  - yarn

before_script:
  - |
    if [ $TRAVIS_BRANCH == "lab" ]; then
       export BUILD_ENV=lab
    elif [ $TRAVIS_BRANCH == "staging" ]; then
       export BUILD_ENV=staging
    elif [ $TRAVIS_BRANCH == "master" ]; then
       export BUILD_ENV=master
    fi

jobs:
  deploy-common: &deploy-common
    provider: s3
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key: ${AWS_SECRET_KEY}
    bucket: ${AWS_S3_BUCKET}
    skip_cleanup: true
    local_dir: "dist"
    on:
      branch:
        - master
        - lab
        - staging
  include:
    - stage: test
      script:
        - yarn lint
    - stage: deploy
      script: 
       - yarn build-index:${BUILD_ENV}
       - export BUILD_PAGE=index
      deploy:
      - <<: *deploy-common
    - stage: deploy
      script: 
      - yarn build-landing:${BUILD_ENV}
      - export BUILD_PAGE=landing
      deploy:
      - <<: *deploy-common
    
after_deploy:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
  - aws configure set aws_secret_access_key ${AWS_SECRET_KEY}
  - |
    if [ $BUILD_PAGE == "index" ]; then
       echo "this is building index"
    elif [ $BUILD_PAGE == "landing" ]; then
       echo "this is building ladning"
    fi
       
